version: '2'
services:
        webclient_guidebox:
                image: "srswinde/indi_webclient:guider"
                ports: 
                        - "3001:3001"
                environment:
                        - INDISERVER=indiserver
#                depends_on:
#                        - "indiserver"
                command: /webclient/websocketd --devconsole --address=0.0.0.0 --port=3001 /webclient/webclient localhost 7623
                network_mode: host

        nginx-server_guidebox:
                image: "nginx"
                ports:
                        - "4002:80"
                volumes:
                        - "${WWW_DIR}/www:/usr/share/nginx/html"
        
        indiserver:
                # stable tag was a version with no error
                # message if vatttel was not communicating
                # We should move the vatttel_not_on
                # to stable when we are sure the
                # update fix doesn't cause any issues
                # -Scott May 2019
                
                
                #                image:  "srswinde/indihex:stable"
                image: "srswinde/indihex:guidebox_secondary"
                ports:
                        - "7623:7623"
                command: /usr/bin/indiserver -p 7623 -v /driver/build/sdev /driver/build/indi-vatt-guidebox
                volumes:
                        - "/home/scott/.mtnops/docker-volumes/indihex/posfile.d:/data/"
                devices:
                        - "/dev/ttyUSB0:/dev/ttyUSB0"
                network_mode: host


