version: '2'
services:
        webclient:
                image: "srswinde/indi_webclient:latest"
                ports: 
                        - "3000:3000"
                environment:
                        - INDISERVER=indiserver
                depends_on:
                        - "indiserver"
                command: /webclient/websocketd --address=0.0.0.0 --devconsole --port=3000 /webclient/webclient localhost
                network_mode: host

        nginx-server:
                image: "nginx"
                ports:
                        - "4001:80"
                volumes:
                        - "./www:/usr/share/nginx/html"
        
        indiserver:
                image: "srswinde/indihex:latest"
                ports:
                        - "7624:7624"
                #command: /usr/bin/indiserver -v /src/sdev
                network_mode: host


