version: '2'
services:
        webclient:
                image: "srswinde/indi_webclient"
                ports: 
                        - "3000:3000"
                environment:
                        - INDISERVER=indiserver
                

        nginx-server:
                image: "nginx"
                ports:
                        - "4001:80"
                volumes:
                        - "./www:/usr/share/nginx/html"

        
        indiserver:
                image: "srswinde/indihex"
                ports:
                        - "7624:7624"


