version: '3'
services:
        webclient:
                image: "srswinde/indi_webclient"
                ports: 
                  - "3000:3000"
                environment:
                        - INDISERVER=indidriver


        nginx-server:
                image: "nginx"
                ports:
                        - "4001:80"
                volumes:
                        - "./www:/usr/share/nginx/html"


                          #        indi-driver:
                          #                image: "scott_indi"
                          #                ports:
                          #                        - "7624:7624"
                          #
                          #
                          #
        
        indidriver:
                image: "srswinde/indihex"
                ports:
                        - "7624:7624"
